   
graphNoDelay = [
    # EVERY node in pipe should be defined here:
    [
        'DUMMY0',  # a node in the pipe topology
        ['DUMMY1', 'DUMMY2']  # the no-delay-successors of this node
        # it means that 
    ],
    [
        'DUMMY1',
        ['DUMMY3']   
    ],
    [
        'DUMMY2',
        ['DUMMY3']
    ],
    [
        'DUMMY3',
        ['']
    ]
]

delayGraph = [
    # only the nodes whose output will be used in the next frame(s) need to be defined here:
    [
        'DUMMY1', # a node in the pipe topology, whose output will be used in the next frame
        [
            ['DUMMY2', 1],  # syntax being [MODULE, DELAY],
        ]
    ],
    [
        'DUMMY3',
        [
            ['DUMMY3', 1]
        ]
        # in this example, the output from DUMMY8 is be used by itself after being 1 frame delayed.
    ]
]


orders = [
    # only the nodes that take more than one input need to be defined here;
    # the order of inputs is defined by algorithm argument lists -- you may refer to the code.
    [
        'DUMMY2',  # a node that takes more than one input
        [
            ['DUMMY0'], # it means the first input of DUMMY3 is DUMMY1's output without frame-delay.
            ['DUMMY1', 1]  # it means the second input of DUMMY3 is DUMMY2's output without frame-delay.
        ]
    ],
    [
        'DUMMY6',
        [
            ['DUMMY1'],
            ['DUMMY2'],
            ['DUMMY3', 1]
        ]
    ]
]