   
graphNoDelay = [
    [
        'DUMMY0',
        ['DUMMY1', 'DUMMY2']
    ],
    [
        'DUMMY1',
        ['DUMMY3']   
    ],
    [
        'DUMMY2',
        ['DUMMY3']
    ],
    [
        'DUMMY3',
        ['DUMMY4', 'DUMMY5']
    ],
    [
        'DUMMY4',
        ['DUMMY6']
    ],
    [
        'DUMMY5',
        ['DUMMY6']
    ],
    [
        'DUMMY6',
        ['DUMMY8']
    ],
    [
        'DUMMY7',
        ['DUMMY6']
    ],
    [
        'DUMMY8',
        ['']
    ]
]

delayGraph = [
    [
        'DUMMY8',
        [
            ['DUMMY8', 1]
        ]
    ],
    [
        'DUMMY1',
        [
            ['DUMMY2', 1],
            ['DUMMY2', 2]
        ]
    ]
]


orders = [
    [
        'DUMMY3',
        [
            ['DUMMY1'], 
            ['DUMMY2']
        ]
    ],
    [
        'DUMMY6',
        [
            ['DUMMY4'],
            ['DUMMY5'],
            ['DUMMY7']
        ]
    ],
    [
        'DUMMY8',
        [
            ['DUMMY6'],
            ['DUMMY8', 1]
        ]
    ],
    [
        'DUMMY2',
        [
            ['DUMMY0'], 
            ['DUMMY1', 1], 
            ['DUMMY1', 2]
        ]
    ]
]