   
graphNoDelay = [
    # EVERY node in pipe should be defined here:
    [
        'DUMMY0',  # a node in the pipe topology
        ['DUMMY1']  # the no-delay-successors of this node
    ],
    [
        'DUMMY1',
        ['DUMMY2']   
    ],
    [
        'DUMMY2',
        [''] # if no successor module, just enter an empty string. do not leave it blank.
    ]
]
