# This is a TOML document.

title = "ISP Config Sample"

[sVinArg]
  rewind = false
  [sVinArg.sAlgoVinArg]
    path = "../data/rawData.raw" # const char* path;
    frameInd = 0 # int frameInd; read i-th frame, i >= 0, WILL BE UPDATED IN THE RUN-TIME; if rewind = true, this will not be updated
    imageFormat = "RAW_RGGB" # IMAGE_FMT imageFormat
    width = 4256 # int width;
    height = 2848 # int height;
    bitDepth = 16 # int bitDepth;
    alignment = 1 # int alignment;

[sCompressionArg]
  [sCompressionArg.sStarTetrixArg]
    Wr = 1 # int
    Wb = 2 # int
  [sCompressionArg.sDWTArg]
    inImgPanelId = 0 # int inImgPanelId; apply dwt to the whole 2D image
    outImgPanelId = 0 # int outImgPanelId;
    orient = "TWO_DIMENSIONAL" # ORIENT orient;
    level = 1 # int level;
    wavelet = "LE_GALL_53" # WAVELET_NAME wavelet;
    padding = "MIRROR" # PADDING padding;

[sCCMArg]
  sAlgoCCMArg = [
    [278, -10, -8],
    [-12, 269, -8],
    [-10, -3, 272]]

[sDummyArg]
data = 3

    